### PR TITLE
Sync Net_IPv6 with pfSense improvements

### PR DESCRIPTION
**Pull request by NewEraCracker**
Hello phil,

I noticed you been working on having Net_IPv6 tweaks merged on official PEAR version, so, I have picked the patches that you submitted to pfSense 2.3 branch and merged the remaining code.

Also modified accessibility of methods _ip2Bin and _bin2Ip to fix a problem affecting pfSense 2.4 as documented here: https://forum.pfsense.org/index.php?topic=117601.0

Hopefully, this tweaks make into pfSense 2.4 and, once again, everything will be nice.

Thanks!

### CODE REVIEW

**Comment by rbgarga** [comment]
If upstream accept to make _ip2Bin and _bin2Ip public they will probably require us to rename them removing the _ from function name. I've committed a band-aid on pfsense to fix them not being available for use and it can be reverted depending of what happens

https://github.com/pfsense/pfsense/commit/de6457345617a6518e58f3ebafa706948534b11a

**Comment by NewEraCracker** [comment]
Okay. I don't care much about the accessibility issue now since you dealt with it. Let's hope the upstream at least accepts the other fixes that improve validation logic.

Thanks!

**Comment by rbgarga** [comment]
I've committed a patch to FreeBSD port adding some fixes that were missed during conversion. It covers all items from https://github.com/pfsense/pfsense/pull/3029

Here is the changes: https://svnweb.freebsd.org/ports?view=revision&revision=421168

**Comment by rbgarga** [comment]
@phil-davis @NewEraCracker FYI, I've opened a bug - https://pear.php.net/bugs/bug.php?id=21107

**Pull request closed without merging**
